import api from "./api";
const unwrap = (response) => response?.data?.data ?? response?.data ?? response ?? {};
export const getWorkflows = async (businessId, params = {}) => unwrap(await api.get(`/workflows/business/${businessId}`, { params }));
export const getWorkflow = async (businessId, workflowId) => unwrap(await api.get(`/workflows/business/${businessId}/${workflowId}`));
export const createWorkflow = async (businessId, data) => unwrap(await api.post(`/workflows/business/${businessId}`, data));
export const updateWorkflow = async (businessId, workflowId, data) => unwrap(await api.patch(`/workflows/business/${businessId}/${workflowId}`, data));
export const updateWorkflowStatus = async (businessId, workflowId, status) => unwrap(await api.patch(`/workflows/business/${businessId}/${workflowId}/status`, { status }));
export const deleteWorkflow = async (businessId, workflowId) => unwrap(await api.delete(`/workflows/business/${businessId}/${workflowId}`));
export const cloneWorkflow = async (businessId, workflowId, name) => unwrap(await api.post(`/workflows/business/${businessId}/${workflowId}/clone`, name ? { name } : {}));
export const executeWorkflow = async (businessId, workflowId, data = {}) => unwrap(await api.post(`/workflows/business/${businessId}/${workflowId}/execute`, data));
export const getWorkflowExecutions = async (businessId, workflowId, params = {}) => unwrap(await api.get(`/workflows/business/${businessId}/${workflowId}/executions`, { params }));
export const getWorkflowExecution = async (businessId, executionId) => unwrap(await api.get(`/workflows/business/${businessId}/executions/${executionId}`));
export default { getWorkflows, getWorkflow, createWorkflow, updateWorkflow, updateWorkflowStatus, deleteWorkflow, cloneWorkflow, executeWorkflow, getWorkflowExecutions, getWorkflowExecution };
