import api from "./api";
const unwrap = (r) => r?.data?.data ?? r?.data ?? r ?? {};
export const getNotifications = async (businessId, params = {}) => unwrap(await api.get(`/notifications/business/${businessId}`, { params }));
export const getUnreadNotificationCount = async (businessId) => unwrap(await api.get(`/notifications/business/${businessId}/unread-count`));
export const getNotification = async (businessId, id) => unwrap(await api.get(`/notifications/business/${businessId}/${id}`));
export const markNotificationRead = async (businessId, id) => unwrap(await api.patch(`/notifications/business/${businessId}/${id}/read`));
export const markAllNotificationsRead = async (businessId) => unwrap(await api.patch(`/notifications/business/${businessId}/read-all`));
export const archiveNotification = async (businessId, id) => unwrap(await api.patch(`/notifications/business/${businessId}/${id}/archive`));
export const deleteNotification = async (businessId, id) => unwrap(await api.delete(`/notifications/business/${businessId}/${id}`));
export default { getNotifications, getUnreadNotificationCount, getNotification, markNotificationRead, markAllNotificationsRead, archiveNotification, deleteNotification };
